"""add_escalation_log

Revision ID: eddc23ba8979
Revises: 29cb72ff2ff0
Create Date: 2026-05-17 21:51:40.503319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eddc23ba8979'
down_revision: Union[str, Sequence[str], None] = '29cb72ff2ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects.postgresql import ENUM
    op.create_table('escalation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('quarter', ENUM('Q1', 'Q2', 'Q3', 'Q4', name='quarter_enum', create_type=False), nullable=False),
    sa.Column('escalation_type', sa.Enum('checkin_overdue', 'checkin_reminder', 'window_open', name='escalation_type_enum'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['goal_cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'cycle_id', 'quarter', 'escalation_type', name='uq_escalation_employee_cycle_quarter_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('escalation_logs')
    # ### end Alembic commands ###
